# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiBuilder.ui'
#
# Created: Thu May 12 12:18:28 2011
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

import os

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(896, 678)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pages = QtGui.QStackedWidget(self.centralwidget)
        self.pages.setObjectName("pages")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtGui.QVBoxLayout(self.page)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtGui.QFrame(self.page)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.frame_4.setPalette(palette)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_5 = QtGui.QLabel(self.frame_4)
        self.label_5.setPixmap(QtGui.QPixmap(os.path.dirname(__file__) + "/icons/startpage.png"))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 3)
        spacerItem3 = QtGui.QSpacerItem(20, 69, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 3, 0, 1, 3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.label_6 = QtGui.QLabel(self.frame_4)
        self.label_6.setMinimumSize(QtCore.QSize(400, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_6.setPalette(palette)
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setScaledContents(False)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 4, 0, 1, 3)
        spacerItem6 = QtGui.QSpacerItem(20, 68, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 5, 0, 1, 3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.open = QtGui.QPushButton(self.frame_4)
        self.open.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.dirname(__file__) + "/icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open.setIcon(icon)
        self.open.setIconSize(QtCore.QSize(64, 64))
        self.open.setDefault(False)
        self.open.setFlat(True)
        self.open.setObjectName("open")
        self.horizontalLayout_4.addWidget(self.open)
        self.newTemplate = QtGui.QPushButton(self.frame_4)
        self.newTemplate.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.dirname(__file__) + "/icons/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newTemplate.setIcon(icon1)
        self.newTemplate.setIconSize(QtCore.QSize(64, 64))
        self.newTemplate.setDefault(False)
        self.newTemplate.setFlat(True)
        self.newTemplate.setObjectName("newTemplate")
        self.horizontalLayout_4.addWidget(self.newTemplate)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 6, 0, 1, 3)
        spacerItem9 = QtGui.QSpacerItem(20, 69, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 8, 0, 1, 3)
        self.continueEditing = QtGui.QPushButton(self.frame_4)
        self.continueEditing.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.continueEditing.setObjectName("continueEditing")
        self.gridLayout_2.addWidget(self.continueEditing, 0, 0, 1, 3)
        self.recentlyOpened = QtGui.QComboBox(self.frame_4)
        self.recentlyOpened.setMinimumSize(QtCore.QSize(300, 0))
        self.recentlyOpened.setObjectName("recentlyOpened")
        self.recentlyOpened.addItem("")
        self.gridLayout_2.addWidget(self.recentlyOpened, 7, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 7, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 7, 2, 1, 1)
        self.verticalLayout.addWidget(self.frame_4)
        self.pages.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame = QtGui.QFrame(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.backToStartPage = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backToStartPage.sizePolicy().hasHeightForWidth())
        self.backToStartPage.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(os.path.dirname(__file__) + "/icons/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backToStartPage.setIcon(icon3)
        self.backToStartPage.setIconSize(QtCore.QSize(32, 32))
        self.backToStartPage.setFlat(True)
        self.backToStartPage.setObjectName("backToStartPage")
        self.horizontalLayout_2.addWidget(self.backToStartPage)
        self.documentation = QtGui.QPushButton(self.frame)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(os.path.dirname(__file__) + "/icons/documentation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.documentation.setIcon(icon4)
        self.documentation.setIconSize(QtCore.QSize(32, 32))
        self.documentation.setFlat(True)
        self.documentation.setObjectName("documentation")
        self.horizontalLayout_2.addWidget(self.documentation)
        self.save = QtGui.QPushButton(self.frame)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(os.path.dirname(__file__) + "/icons/filesave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save.setIcon(icon5)
        self.save.setIconSize(QtCore.QSize(32, 32))
        self.save.setAutoDefault(False)
        self.save.setFlat(True)
        self.save.setObjectName("save")
        self.horizontalLayout_2.addWidget(self.save)
        self.saveAs = QtGui.QPushButton(self.frame)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(os.path.dirname(__file__) + "/icons/filesaveas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveAs.setIcon(icon6)
        self.saveAs.setIconSize(QtCore.QSize(32, 32))
        self.saveAs.setFlat(True)
        self.saveAs.setObjectName("saveAs")
        self.horizontalLayout_2.addWidget(self.saveAs)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.reload = QtGui.QPushButton(self.frame)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(os.path.dirname(__file__) + "/icons/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reload.setIcon(icon7)
        self.reload.setIconSize(QtCore.QSize(32, 32))
        self.reload.setFlat(True)
        self.reload.setObjectName("reload")
        self.horizontalLayout_2.addWidget(self.reload)
        self.verticalLayout_11.addWidget(self.frame)
        self.splitter_2 = QtGui.QSplitter(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setOpaqueResize(True)
        self.splitter_2.setHandleWidth(7)
        self.splitter_2.setObjectName("splitter_2")
        self.frame_2 = QtGui.QFrame(self.splitter_2)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setSpacing(-1)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setPixmap(QtGui.QPixmap(os.path.dirname(__file__) + "/icons/find.png"))
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.filter = QtGui.QLineEdit(self.frame_2)
        self.filter.setObjectName("filter")
        self.horizontalLayout_8.addWidget(self.filter)
        self.cancelFilter = QtGui.QToolButton(self.frame_2)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(os.path.dirname(__file__) + "/icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelFilter.setIcon(icon8)
        self.cancelFilter.setIconSize(QtCore.QSize(16, 16))
        self.cancelFilter.setAutoRaise(True)
        self.cancelFilter.setObjectName("cancelFilter")
        self.horizontalLayout_8.addWidget(self.cancelFilter)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.browserView = QtGui.QStackedWidget(self.frame_2)
        self.browserView.setObjectName("browserView")
        self.elementsFrame = QtGui.QWidget()
        self.elementsFrame.setObjectName("elementsFrame")
        self.gridLayout = QtGui.QGridLayout(self.elementsFrame)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.elements = QtGui.QToolBox(self.elementsFrame)
        self.elements.setObjectName("elements")
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 166, 572))
        self.page_4.setObjectName("page_4")
        self.elements.addItem(self.page_4, "")
        self.gridLayout.addWidget(self.elements, 0, 0, 1, 1)
        self.browserView.addWidget(self.elementsFrame)
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName("page_7")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.page_7)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.searchResults = QtGui.QListWidget(self.page_7)
        self.searchResults.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.searchResults.setIconSize(QtCore.QSize(32, 32))
        self.searchResults.setObjectName("searchResults")
        self.verticalLayout_12.addWidget(self.searchResults)
        self.browserView.addWidget(self.page_7)
        self.verticalLayout_8.addWidget(self.browserView)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(7)
        self.splitter.setObjectName("splitter")
        self.frame_3 = QtGui.QFrame(self.splitter)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.preview = QtWebKit.QWebView(self.frame_3)
        self.preview.setUrl(QtCore.QUrl("about:blank"))
        self.preview.setObjectName("preview")
        self.verticalLayout_2.addWidget(self.preview)
        self.frame_5 = QtGui.QFrame(self.splitter)
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtGui.QTabWidget(self.frame_5)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.rearrange = QtGui.QPushButton(self.tab)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(os.path.dirname(__file__) + "/icons/rearrange.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rearrange.setIcon(icon9)
        self.rearrange.setIconSize(QtCore.QSize(22, 22))
        self.rearrange.setCheckable(True)
        self.rearrange.setFlat(True)
        self.rearrange.setObjectName("rearrange")
        self.horizontalLayout_7.addWidget(self.rearrange)
        self.expand = QtGui.QPushButton(self.tab)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(os.path.dirname(__file__) + "/icons/expand.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.expand.setIcon(icon10)
        self.expand.setIconSize(QtCore.QSize(22, 22))
        self.expand.setFlat(True)
        self.expand.setObjectName("expand")
        self.horizontalLayout_7.addWidget(self.expand)
        self.collapse = QtGui.QPushButton(self.tab)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(os.path.dirname(__file__) + "/icons/collapse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.collapse.setIcon(icon11)
        self.collapse.setIconSize(QtCore.QSize(22, 22))
        self.collapse.setFlat(True)
        self.collapse.setObjectName("collapse")
        self.horizontalLayout_7.addWidget(self.collapse)
        self.deleteFromTree = QtGui.QPushButton(self.tab)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(os.path.dirname(__file__) + "/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteFromTree.setIcon(icon12)
        self.deleteFromTree.setIconSize(QtCore.QSize(22, 22))
        self.deleteFromTree.setFlat(True)
        self.deleteFromTree.setObjectName("deleteFromTree")
        self.horizontalLayout_7.addWidget(self.deleteFromTree)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.baseLayout = QtGui.QComboBox(self.tab)
        self.baseLayout.setObjectName("baseLayout")
        self.baseLayout.addItem("")
        self.baseLayout.addItem("")
        self.baseLayout.addItem("")
        self.baseLayout.addItem("")
        self.baseLayout.addItem("")
        self.horizontalLayout_7.addWidget(self.baseLayout)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.tree = QtGui.QTreeWidget(self.tab)
        self.tree.setDragEnabled(True)
        self.tree.setDragDropOverwriteMode(False)
        self.tree.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.tree.setAlternatingRowColors(True)
        self.tree.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tree.setIconSize(QtCore.QSize(32, 32))
        self.tree.setHeaderHidden(True)
        self.tree.setColumnCount(5)
        self.tree.setObjectName("tree")
        self.tree.header().setVisible(False)
        self.tree.header().setCascadingSectionResizes(False)
        self.tree.header().setDefaultSectionSize(92)
        self.tree.header().setSortIndicatorShown(False)
        self.verticalLayout_5.addWidget(self.tree)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.wuiTemplate = QtGui.QTextEdit(self.tab_2)
        self.wuiTemplate.setObjectName("wuiTemplate")
        self.verticalLayout_4.addWidget(self.wuiTemplate)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.frame_6 = QtGui.QFrame(self.splitter_2)
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget_2 = QtGui.QTabWidget(self.frame_6)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.propertiesTab = QtGui.QWidget()
        self.propertiesTab.setObjectName("propertiesTab")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.propertiesTab)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.scrollArea = QtGui.QScrollArea(self.propertiesTab)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 164, 609))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.properties = QtGui.QTableWidget(self.scrollAreaWidgetContents)
        self.properties.setObjectName("properties")
        self.properties.setColumnCount(0)
        self.properties.setRowCount(0)
        self.verticalLayout_9.addWidget(self.properties)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_9.addWidget(self.scrollArea)
        self.tabWidget_2.addTab(self.propertiesTab, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.info = QtGui.QTextBrowser(self.tab_4)
        self.info.setFrameShape(QtGui.QFrame.NoFrame)
        self.info.setFrameShadow(QtGui.QFrame.Plain)
        self.info.setLineWidth(0)
        self.info.setObjectName("info")
        self.verticalLayout_10.addWidget(self.info)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.verticalLayout_6.addWidget(self.tabWidget_2)
        self.verticalLayout_11.addWidget(self.splitter_2)
        self.pages.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.pages)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(0)
        self.browserView.setCurrentIndex(0)
        self.elements.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_4.setStyleSheet(QtGui.QApplication.translate("MainWindow", "\n"
"    background:white;", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setStyleSheet(QtGui.QApplication.translate("MainWindow", "font-size:15px;", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Welcome to WebElement GUI Builder version 0.5. A tool designed to allow anyone to easily create user interfaces for widgets and web applications with an emphasis on element reuse.", None, QtGui.QApplication.UnicodeUTF8))
        self.open.setText(QtGui.QApplication.translate("MainWindow", "Open Template", None, QtGui.QApplication.UnicodeUTF8))
        self.newTemplate.setText(QtGui.QApplication.translate("MainWindow", "Create New Template", None, QtGui.QApplication.UnicodeUTF8))
        self.continueEditing.setText(QtGui.QApplication.translate("MainWindow", "Continues Editing \'file\' >", None, QtGui.QApplication.UnicodeUTF8))
        self.recentlyOpened.setItemText(0, QtGui.QApplication.translate("MainWindow", "Open Recent...", None, QtGui.QApplication.UnicodeUTF8))
        self.frame.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background:#D4D4D4;", None, QtGui.QApplication.UnicodeUTF8))
        self.backToStartPage.setText(QtGui.QApplication.translate("MainWindow", "Back to start page", None, QtGui.QApplication.UnicodeUTF8))
        self.documentation.setText(QtGui.QApplication.translate("MainWindow", "Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.save.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAs.setText(QtGui.QApplication.translate("MainWindow", "Save as..", None, QtGui.QApplication.UnicodeUTF8))
        self.reload.setText(QtGui.QApplication.translate("MainWindow", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.splitter_2.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background-color:rgb(204, 204, 204);", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_2.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background:white;", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelFilter.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.elements.setItemText(self.elements.indexOf(self.page_4), QtGui.QApplication.translate("MainWindow", "Page 2", None, QtGui.QApplication.UnicodeUTF8))
        self.splitter.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background-color:rgb(204, 204, 204);", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_3.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background:white;", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_5.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background:white;", None, QtGui.QApplication.UnicodeUTF8))
        self.rearrange.setText(QtGui.QApplication.translate("MainWindow", "Rearrange", None, QtGui.QApplication.UnicodeUTF8))
        self.expand.setText(QtGui.QApplication.translate("MainWindow", "Expand", None, QtGui.QApplication.UnicodeUTF8))
        self.collapse.setText(QtGui.QApplication.translate("MainWindow", "Collapse", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteFromTree.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Layout:", None, QtGui.QApplication.UnicodeUTF8))
        self.baseLayout.setItemText(0, QtGui.QApplication.translate("MainWindow", "flow", None, QtGui.QApplication.UnicodeUTF8))
        self.baseLayout.setItemText(1, QtGui.QApplication.translate("MainWindow", "fields", None, QtGui.QApplication.UnicodeUTF8))
        self.baseLayout.setItemText(2, QtGui.QApplication.translate("MainWindow", "box", None, QtGui.QApplication.UnicodeUTF8))
        self.baseLayout.setItemText(3, QtGui.QApplication.translate("MainWindow", "vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.baseLayout.setItemText(4, QtGui.QApplication.translate("MainWindow", "horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.tree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Element", None, QtGui.QApplication.UnicodeUTF8))
        self.tree.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Id", None, QtGui.QApplication.UnicodeUTF8))
        self.tree.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tree.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Accessor", None, QtGui.QApplication.UnicodeUTF8))
        self.tree.headerItem().setText(4, QtGui.QApplication.translate("MainWindow", "renderingOrder", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Tree Structure", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Template", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_6.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background:white;", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.propertiesTab), QtGui.QApplication.translate("MainWindow", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
