# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiBuilder.ui'
#
# Created: Thu Apr  4 12:40:02 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1057, 732)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet(_fromUtf8(""))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pages = QtGui.QStackedWidget(self.centralwidget)
        self.pages.setObjectName(_fromUtf8("pages"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout = QtGui.QVBoxLayout(self.page)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_4 = QtGui.QFrame(self.page)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.frame_4.setPalette(palette)
        self.frame_4.setStyleSheet(_fromUtf8("#frame_4{\n"
"    background:white;\n"
"}"))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.continueEditing = QtGui.QPushButton(self.frame_4)
        self.continueEditing.setStyleSheet(_fromUtf8(""))
        self.continueEditing.setObjectName(_fromUtf8("continueEditing"))
        self.verticalLayout_13.addWidget(self.continueEditing)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_5 = QtGui.QLabel(self.frame_4)
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8("icons/startpage.png")))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtGui.QSpacerItem(20, 69, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem3)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.recentlyOpened = QtGui.QComboBox(self.frame_4)
        self.recentlyOpened.setMinimumSize(QtCore.QSize(300, 0))
        self.recentlyOpened.setObjectName(_fromUtf8("recentlyOpened"))
        self.recentlyOpened.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.recentlyOpened)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.verticalLayout_13.addLayout(self.horizontalLayout_10)
        spacerItem6 = QtGui.QSpacerItem(20, 77, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_13.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.open = QtGui.QPushButton(self.frame_4)
        self.open.setAccessibleName(_fromUtf8(""))
        self.open.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.open.setStyleSheet(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open.setIcon(icon)
        self.open.setIconSize(QtCore.QSize(64, 64))
        self.open.setDefault(False)
        self.open.setFlat(False)
        self.open.setProperty("class", _fromUtf8(""))
        self.open.setObjectName(_fromUtf8("open"))
        self.horizontalLayout_4.addWidget(self.open)
        self.newTemplate = QtGui.QPushButton(self.frame_4)
        self.newTemplate.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.newTemplate.setStatusTip(_fromUtf8(""))
        self.newTemplate.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newTemplate.setIcon(icon1)
        self.newTemplate.setIconSize(QtCore.QSize(64, 64))
        self.newTemplate.setDefault(False)
        self.newTemplate.setFlat(False)
        self.newTemplate.setObjectName(_fromUtf8("newTemplate"))
        self.horizontalLayout_4.addWidget(self.newTemplate)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.verticalLayout_13.addLayout(self.horizontalLayout_6)
        spacerItem9 = QtGui.QSpacerItem(20, 69, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem9)
        self.verticalLayout.addWidget(self.frame_4)
        self.pages.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.toolbar = QtGui.QFrame(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbar.sizePolicy().hasHeightForWidth())
        self.toolbar.setSizePolicy(sizePolicy)
        self.toolbar.setStyleSheet(_fromUtf8(""))
        self.toolbar.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolbar.setFrameShadow(QtGui.QFrame.Raised)
        self.toolbar.setObjectName(_fromUtf8("toolbar"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.toolbar)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.backToStartPage = QtGui.QPushButton(self.toolbar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backToStartPage.sizePolicy().hasHeightForWidth())
        self.backToStartPage.setSizePolicy(sizePolicy)
        self.backToStartPage.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/back.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backToStartPage.setIcon(icon2)
        self.backToStartPage.setIconSize(QtCore.QSize(32, 32))
        self.backToStartPage.setFlat(False)
        self.backToStartPage.setObjectName(_fromUtf8("backToStartPage"))
        self.horizontalLayout_2.addWidget(self.backToStartPage)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.reload = QtGui.QPushButton(self.toolbar)
        self.reload.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/reload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reload.setIcon(icon3)
        self.reload.setIconSize(QtCore.QSize(32, 32))
        self.reload.setFlat(False)
        self.reload.setObjectName(_fromUtf8("reload"))
        self.horizontalLayout_2.addWidget(self.reload)
        self.save = QtGui.QPushButton(self.toolbar)
        self.save.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("icons/filesave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save.setIcon(icon4)
        self.save.setIconSize(QtCore.QSize(32, 32))
        self.save.setAutoDefault(False)
        self.save.setFlat(False)
        self.save.setObjectName(_fromUtf8("save"))
        self.horizontalLayout_2.addWidget(self.save)
        self.saveAs = QtGui.QPushButton(self.toolbar)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("icons/filesaveas.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveAs.setIcon(icon5)
        self.saveAs.setIconSize(QtCore.QSize(32, 32))
        self.saveAs.setFlat(False)
        self.saveAs.setObjectName(_fromUtf8("saveAs"))
        self.horizontalLayout_2.addWidget(self.saveAs)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.documentation = QtGui.QPushButton(self.toolbar)
        self.documentation.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("icons/documentation.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.documentation.setIcon(icon6)
        self.documentation.setIconSize(QtCore.QSize(32, 32))
        self.documentation.setFlat(False)
        self.documentation.setObjectName(_fromUtf8("documentation"))
        self.horizontalLayout_2.addWidget(self.documentation)
        self.verticalLayout_11.addWidget(self.toolbar)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.addElementFrame = QtGui.QFrame(self.page_2)
        self.addElementFrame.setMinimumSize(QtCore.QSize(240, 0))
        self.addElementFrame.setMaximumSize(QtCore.QSize(240, 16777215))
        self.addElementFrame.setStyleSheet(_fromUtf8("#addElementFrame{background-white;}"))
        self.addElementFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.addElementFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.addElementFrame.setObjectName(_fromUtf8("addElementFrame"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.addElementFrame)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(1)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label = QtGui.QLabel(self.addElementFrame)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("icons/find.png")))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_8.addWidget(self.label)
        self.filter = QtGui.QLineEdit(self.addElementFrame)
        self.filter.setObjectName(_fromUtf8("filter"))
        self.horizontalLayout_8.addWidget(self.filter)
        self.cancelFilter = QtGui.QToolButton(self.addElementFrame)
        self.cancelFilter.setEnabled(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("icons/cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelFilter.setIcon(icon7)
        self.cancelFilter.setIconSize(QtCore.QSize(16, 16))
        self.cancelFilter.setAutoRaise(True)
        self.cancelFilter.setObjectName(_fromUtf8("cancelFilter"))
        self.horizontalLayout_8.addWidget(self.cancelFilter)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.browserView = QtGui.QStackedWidget(self.addElementFrame)
        self.browserView.setObjectName(_fromUtf8("browserView"))
        self.elementsFrame = QtGui.QWidget()
        self.elementsFrame.setObjectName(_fromUtf8("elementsFrame"))
        self.gridLayout = QtGui.QGridLayout(self.elementsFrame)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.elements = QtGui.QToolBox(self.elementsFrame)
        self.elements.setObjectName(_fromUtf8("elements"))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 240, 593))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.elements.addItem(self.page_4, _fromUtf8(""))
        self.gridLayout.addWidget(self.elements, 0, 0, 1, 1)
        self.browserView.addWidget(self.elementsFrame)
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.page_7)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.searchResults = QtGui.QListWidget(self.page_7)
        self.searchResults.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.searchResults.setIconSize(QtCore.QSize(32, 32))
        self.searchResults.setObjectName(_fromUtf8("searchResults"))
        self.verticalLayout_12.addWidget(self.searchResults)
        self.browserView.addWidget(self.page_7)
        self.verticalLayout_8.addWidget(self.browserView)
        self.horizontalLayout_12.addWidget(self.addElementFrame)
        self.splitter = QtGui.QSplitter(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setStyleSheet(_fromUtf8("#splitter{background-color:rgb(204, 204, 204);}"))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(7)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame_3 = QtGui.QFrame(self.splitter)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.preview = QtWebKit.QWebView(self.frame_3)
        self.preview.setStyleSheet(_fromUtf8(""))
        self.preview.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.preview.setObjectName(_fromUtf8("preview"))
        self.verticalLayout_2.addWidget(self.preview)
        self.treeStructureFrame = QtGui.QFrame(self.splitter)
        self.treeStructureFrame.setStyleSheet(_fromUtf8("#frame_5\n"
"{\n"
"background-color:white;\n"
"}"))
        self.treeStructureFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.treeStructureFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.treeStructureFrame.setObjectName(_fromUtf8("treeStructureFrame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.treeStructureFrame)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.treeStructureFrame)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setStyleSheet(_fromUtf8("#tab\n"
"{\n"
"background:white;\n"
"}"))
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8("icons/find.png")))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_14.addWidget(self.label_4)
        self.filterTree = QtGui.QLineEdit(self.tab)
        self.filterTree.setObjectName(_fromUtf8("filterTree"))
        self.horizontalLayout_14.addWidget(self.filterTree)
        self.cancelTreeFilter = QtGui.QToolButton(self.tab)
        self.cancelTreeFilter.setEnabled(True)
        self.cancelTreeFilter.setIcon(icon7)
        self.cancelTreeFilter.setIconSize(QtCore.QSize(16, 16))
        self.cancelTreeFilter.setAutoRaise(True)
        self.cancelTreeFilter.setObjectName(_fromUtf8("cancelTreeFilter"))
        self.horizontalLayout_14.addWidget(self.cancelTreeFilter)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_14)
        spacerItem12 = QtGui.QSpacerItem(17, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setStyleSheet(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_7.addWidget(self.label_2)
        self.baseLayout = QtGui.QComboBox(self.tab)
        self.baseLayout.setStyleSheet(_fromUtf8("background:white;"))
        self.baseLayout.setObjectName(_fromUtf8("baseLayout"))
        self.baseLayout.addItem(_fromUtf8(""))
        self.baseLayout.addItem(_fromUtf8(""))
        self.baseLayout.addItem(_fromUtf8(""))
        self.baseLayout.addItem(_fromUtf8(""))
        self.baseLayout.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.baseLayout)
        self.expand = QtGui.QPushButton(self.tab)
        self.expand.setStyleSheet(_fromUtf8(""))
        self.expand.setIconSize(QtCore.QSize(22, 22))
        self.expand.setFlat(False)
        self.expand.setObjectName(_fromUtf8("expand"))
        self.horizontalLayout_7.addWidget(self.expand)
        self.collapse = QtGui.QPushButton(self.tab)
        self.collapse.setStyleSheet(_fromUtf8(""))
        self.collapse.setIconSize(QtCore.QSize(22, 22))
        self.collapse.setFlat(False)
        self.collapse.setObjectName(_fromUtf8("collapse"))
        self.horizontalLayout_7.addWidget(self.collapse)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.tree = QtGui.QTreeWidget(self.tab)
        self.tree.setStyleSheet(_fromUtf8("background:white;"))
        self.tree.setDragEnabled(True)
        self.tree.setDragDropOverwriteMode(False)
        self.tree.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.tree.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.tree.setAlternatingRowColors(True)
        self.tree.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tree.setIconSize(QtCore.QSize(32, 32))
        self.tree.setHeaderHidden(True)
        self.tree.setColumnCount(5)
        self.tree.setObjectName(_fromUtf8("tree"))
        self.tree.header().setVisible(False)
        self.tree.header().setCascadingSectionResizes(False)
        self.tree.header().setDefaultSectionSize(92)
        self.tree.header().setSortIndicatorShown(False)
        self.verticalLayout_5.addWidget(self.tree)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.wuiXML = QtGui.QTextEdit(self.tab_2)
        self.wuiXML.setObjectName(_fromUtf8("wuiXML"))
        self.verticalLayout_4.addWidget(self.wuiXML)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.wuiSHPAML = QtGui.QTextEdit(self.tab_3)
        self.wuiSHPAML.setObjectName(_fromUtf8("wuiSHPAML"))
        self.verticalLayout_7.addWidget(self.wuiSHPAML)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_12.addWidget(self.splitter)
        self.elementFrame = QtGui.QFrame(self.page_2)
        self.elementFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.elementFrame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.elementFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.elementFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.elementFrame.setObjectName(_fromUtf8("elementFrame"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.elementFrame)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tabWidget_2 = QtGui.QTabWidget(self.elementFrame)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.propertiesTab = QtGui.QWidget()
        self.propertiesTab.setObjectName(_fromUtf8("propertiesTab"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.propertiesTab)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.scrollArea = QtGui.QScrollArea(self.propertiesTab)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 296, 626))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8("icons/find.png")))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_13.addWidget(self.label_3)
        self.filterProperties = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.filterProperties.setObjectName(_fromUtf8("filterProperties"))
        self.horizontalLayout_13.addWidget(self.filterProperties)
        self.cancelPropertyFilter = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.cancelPropertyFilter.setEnabled(True)
        self.cancelPropertyFilter.setIcon(icon7)
        self.cancelPropertyFilter.setIconSize(QtCore.QSize(16, 16))
        self.cancelPropertyFilter.setAutoRaise(True)
        self.cancelPropertyFilter.setObjectName(_fromUtf8("cancelPropertyFilter"))
        self.horizontalLayout_13.addWidget(self.cancelPropertyFilter)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.properties = QtGui.QTableWidget(self.scrollAreaWidgetContents)
        self.properties.setLineWidth(1)
        self.properties.setShowGrid(False)
        self.properties.setGridStyle(QtCore.Qt.NoPen)
        self.properties.setWordWrap(True)
        self.properties.setObjectName(_fromUtf8("properties"))
        self.properties.setColumnCount(0)
        self.properties.setRowCount(0)
        self.properties.horizontalHeader().setVisible(False)
        self.properties.horizontalHeader().setHighlightSections(False)
        self.properties.verticalHeader().setVisible(False)
        self.properties.verticalHeader().setHighlightSections(False)
        self.verticalLayout_9.addWidget(self.properties)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_9.addWidget(self.scrollArea)
        self.tabWidget_2.addTab(self.propertiesTab, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.info = QtGui.QTextBrowser(self.tab_4)
        self.info.setFrameShape(QtGui.QFrame.NoFrame)
        self.info.setFrameShadow(QtGui.QFrame.Plain)
        self.info.setLineWidth(0)
        self.info.setObjectName(_fromUtf8("info"))
        self.verticalLayout_10.addWidget(self.info)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.tabWidget_2)
        self.horizontalLayout_12.addWidget(self.elementFrame)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.toggleElementsFrame = QtGui.QPushButton(self.page_2)
        self.toggleElementsFrame.setMinimumSize(QtCore.QSize(240, 0))
        self.toggleElementsFrame.setMaximumSize(QtCore.QSize(240, 16777215))
        self.toggleElementsFrame.setCheckable(True)
        self.toggleElementsFrame.setChecked(True)
        self.toggleElementsFrame.setFlat(False)
        self.toggleElementsFrame.setObjectName(_fromUtf8("toggleElementsFrame"))
        self.horizontalLayout_11.addWidget(self.toggleElementsFrame)
        self.toggleTreeStructureFrame = QtGui.QPushButton(self.page_2)
        self.toggleTreeStructureFrame.setCheckable(True)
        self.toggleTreeStructureFrame.setChecked(True)
        self.toggleTreeStructureFrame.setObjectName(_fromUtf8("toggleTreeStructureFrame"))
        self.horizontalLayout_11.addWidget(self.toggleTreeStructureFrame)
        self.toggleElementFrame = QtGui.QPushButton(self.page_2)
        self.toggleElementFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.toggleElementFrame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.toggleElementFrame.setCheckable(True)
        self.toggleElementFrame.setChecked(True)
        self.toggleElementFrame.setObjectName(_fromUtf8("toggleElementFrame"))
        self.horizontalLayout_11.addWidget(self.toggleElementFrame)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.pages.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.pages)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(0)
        self.browserView.setCurrentIndex(0)
        self.elements.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QObject.connect(self.toggleElementsFrame, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.addElementFrame.setVisible)
        QtCore.QObject.connect(self.toggleElementFrame, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.elementFrame.setVisible)
        QtCore.QObject.connect(self.toggleTreeStructureFrame, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.treeStructureFrame.setVisible)
        QtCore.QObject.connect(self.toggleElementsFrame, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.filter.setFocus)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.continueEditing.setText(QtGui.QApplication.translate("MainWindow", "Continues Editing \'file\' >", None, QtGui.QApplication.UnicodeUTF8))
        self.recentlyOpened.setItemText(0, QtGui.QApplication.translate("MainWindow", "Open Recent...", None, QtGui.QApplication.UnicodeUTF8))
        self.open.setText(QtGui.QApplication.translate("MainWindow", "Open Template", None, QtGui.QApplication.UnicodeUTF8))
        self.newTemplate.setText(QtGui.QApplication.translate("MainWindow", "Create New Template", None, QtGui.QApplication.UnicodeUTF8))
        self.newTemplate.setProperty("class", QtGui.QApplication.translate("MainWindow", "MainAction", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAs.setText(QtGui.QApplication.translate("MainWindow", "Save as..", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelFilter.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_3.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background:white;", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelTreeFilter.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Layout:", None, QtGui.QApplication.UnicodeUTF8))
        self.baseLayout.setItemText(0, QtGui.QApplication.translate("MainWindow", "flow", None, QtGui.QApplication.UnicodeUTF8))
        self.baseLayout.setItemText(1, QtGui.QApplication.translate("MainWindow", "fields", None, QtGui.QApplication.UnicodeUTF8))
        self.baseLayout.setItemText(2, QtGui.QApplication.translate("MainWindow", "box", None, QtGui.QApplication.UnicodeUTF8))
        self.baseLayout.setItemText(3, QtGui.QApplication.translate("MainWindow", "vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.baseLayout.setItemText(4, QtGui.QApplication.translate("MainWindow", "horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.expand.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.collapse.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.tree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Element", None, QtGui.QApplication.UnicodeUTF8))
        self.tree.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Id", None, QtGui.QApplication.UnicodeUTF8))
        self.tree.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tree.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Accessor", None, QtGui.QApplication.UnicodeUTF8))
        self.tree.headerItem().setText(4, QtGui.QApplication.translate("MainWindow", "renderingOrder", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Tree Structure", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "XML", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "SHPAML", None, QtGui.QApplication.UnicodeUTF8))
        self.elementFrame.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background:white;", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelPropertyFilter.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.propertiesTab), QtGui.QApplication.translate("MainWindow", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.toggleElementsFrame.setText(QtGui.QApplication.translate("MainWindow", "Add Element", None, QtGui.QApplication.UnicodeUTF8))
        self.toggleTreeStructureFrame.setText(QtGui.QApplication.translate("MainWindow", "View / Modify Tree Structure", None, QtGui.QApplication.UnicodeUTF8))
        self.toggleElementFrame.setText(QtGui.QApplication.translate("MainWindow", "Element Information", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
